language: node_js
sudo: required
dist: trusty
addons:
  chrome: stable

before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'

cache:
  directories:
    - ~/.npm
notifications:
  email: false

node_js:
  - '8'

stages:
  - 'Tests'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  include:
    - stage: 'Tests'
      name: 'Conventional Commits'
      script: commitlint-travis
    - name: 'Fixed Dependencies'
      install: yarn install --non-interactive
    - name: 'Floating Dependencies'
      after_install: yarn global add codecov
      script: node_modules/.bin/nyc yarn test
      after_script: codecov

    - stage: 'Deploy'
      name: 'Publish to npm'
      install:
        - yarn install --non-interactive
      script: yarn semantic-release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
